In [1]:
import pandas as pd
import numpy as np

In [2]:
def CleaningData(d):
    
    df = d.copy()
    df['Gender'] = df['Gender'].astype('category')
    df['Gender'].cat.categories = [-1,1]
    df['Gender'] = df['Gender'].astype('float')
    
    df['ECOG PS'] = df['ECOG PS'].where(df['Hx Smoking'] != 'unknown' )
    df['ECOG PS'] = df['ECOG PS'].astype('category')
    df['ECOG PS'].cat.categories = [1,2,3,4,5, 0]
    df['ECOG PS'] = df['ECOG PS'].astype('float')
    
    
    df['Hx Smoking'] = df['Hx Smoking'].astype('category')
    df['Hx Smoking'].cat.categories = [3, 2, 1]
    df['Hx Smoking'] = df['Hx Smoking'].astype('float')
    #df['Hx Drinking'] = df['Hx Drinking'].where(df['Hx Drinking'] != 'unknown' )
    
    df['Hx Drinking'] = df['Hx Drinking'].astype('category')
    df['Hx Drinking'].cat.categories = [4, 5, 2, 3, 1, 0]
    df['Hx Drinking'] = df['Hx Drinking'].astype('float')
    
    df['T'] = df['T'].astype('category')
    df['T'].cat.categories = [1,2,3,4,5]
    df['T'] = df['T'].astype('float')
    
    df['N'] = df['N'].astype('category')
    df['N'].cat.categories = [1,2,3,4,5,6]
    df['N'] = df['N'].astype('float')
    
 
    
    df['Stage'] = df['Stage'].astype('category')
    df['Stage'].cat.categories = [4, 5, 2, 3, 1]
    df['Stage'] = df['Stage'].astype('float')
    
    df['p16'] = df['p16'].astype('category')
    df['p16'].cat.categories = [-10,10,0]
    df['p16'] = df['p16'].astype('float')
 
    df = pd.get_dummies(df, prefix='Sunsite_',  columns=['Subsite'])
    
    return df

In [3]:
df1 = pd.read_csv("OPC/clinical_info_raw.csv")
feature = pd.read_csv("OPC/radiomic_features_name.csv")

In [4]:
df = df1[['ID','Age','Gender','ECOG PS', 'Smoking PY', 'Hx Smoking', 'Hx Drinking', 'Subsite', 'T', 'N','Stage', 'p16']].copy()

In [5]:
f = feature.T
f.reset_index(inplace = True)
f = f.merge(df, left_on = 'index' , right_on = 'ID')

In [12]:
clinic = f[['ID','Age','Gender','ECOG PS', 'Smoking PY', 'Hx Smoking', 'Hx Drinking', 'Subsite', 'T', 'N','Stage', 'p16',26 ]].copy()

In [13]:
clinic = CleaningData(clinic)

In [11]:
c = clinic.set_index('ID').T
c = c.reset_index()
c.drop('index', axis = 1, inplace = True)
c.to_csv("OPC/VolumeAndClinic.csv")

In [16]:
c[['ID','Age','Gender','ECOG PS', 'Smoking PY', 'Hx Smoking', 'Hx Drinking', 'Subsite', 'T', 'N','Stage', 'p16' ]].to_csv("OPC/VolumeAndClinic.csv")

In [39]:
from sklearn.model_selection import StratifiedShuffleSplit
X = np.array([[1, 2], [3, 4], [1, 2], [3, 4]])
y = np.array([0, 0, 1, 1])
sss = StratifiedShuffleSplit(n_splits=3, test_size=0.5, random_state=6)
sss.get_n_splits(X, y)

3

In [40]:
for train_index, test_index in sss.split(X, y):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]

TRAIN: [1 2] TEST: [3 0]
TRAIN: [1 2] TEST: [3 0]
TRAIN: [1 3] TEST: [0 2]

In [41]:
c

ID,FHBO001,FHBO003,FHBO004,FHBO005,FHBO006,FHBO007,FHBO010,FHBO011,FHBO012,FHBO013,...,FHBO651,FHBO652,FHBO653,FHBO654,FHBO655,FHBO656,FHBO658,FHBO659,FHBO660,FHBO661
0,62.6,59.7,61,59.7,68.7,54.4,57.1,63.5,63.6,57.2,...,55.4,58.1,68.3,58.3,71.3,53.9,57,66.2,82.5,80.5
1,-1,-1,1,1,1,-1,-1,-1,-1,1,...,-1,-1,1,1,1,-1,1,-1,-1,1
2,1,1,1,1,1,1,1,2,1,1,...,2,1,2,1,2,1,2,2,2,3
3,50,0,5,40,40,50,2,0,0,15,...,30,5,0,50,50,5,60,0,50,45
4,2,1,3,3,2,2,2,1,1,2,...,3,2,1,2,2,3,2,1,2,2
5,2,1,3,3,1,1,3,1,1,1,...,3,3,1,5,2,4,1,1,2,2
6,5,5,2,3,3,2,1,5,2,2,...,3,3,2,2,2,2,3,4,2,2
7,5,1,3,1,5,5,3,5,1,1,...,5,2,4,1,1,4,1,1,1,1
8,1,1,3,2,3,3,3,1,5,5,...,3,2,3,5,5,3,2,3,5,5
9,-10,-10,10,10,0,0,10,0,10,0,...,10,10,10,10,0,10,10,-10,-10,-10
10,31419.7,43733.6,0,22302.6,26906.9,0,0,156163,0,16943,...,21911.6,28919.2,63350.6,15787.1,22863.4,8716.57,26060.1,38648.6,11601.5,33393.8
11,0,0,0,0,1,0,0,1,0,0,...,0,0,1,0,0,0,0,1,0,0
12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,1
14,0,0,0,0,0,0,0,0,1,1,...,1,0,0,0,0,0,1,0,0,0
15,0,0,0,0,0,0,0,0,0,0,...,0,1,0,1,0,0,0,0,0,0
16,0,1,1,0,0,1,1,0,0,0,...,0,0,0,0,0,1,0,0,0,0
17,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [61]:
c.iloc[[2,3],0]

KeyError: '[1.0 50.0] not in index'

In [45]:
c

ID,FHBO001,FHBO003,FHBO004,FHBO005,FHBO006,FHBO007,FHBO010,FHBO011,FHBO012,FHBO013,...,FHBO651,FHBO652,FHBO653,FHBO654,FHBO655,FHBO656,FHBO658,FHBO659,FHBO660,FHBO661
0,62.6,59.7,61,59.7,68.7,54.4,57.1,63.5,63.6,57.2,...,55.4,58.1,68.3,58.3,71.3,53.9,57,66.2,82.5,80.5
1,-1,-1,1,1,1,-1,-1,-1,-1,1,...,-1,-1,1,1,1,-1,1,-1,-1,1
2,1,1,1,1,1,1,1,2,1,1,...,2,1,2,1,2,1,2,2,2,3
3,50,0,5,40,40,50,2,0,0,15,...,30,5,0,50,50,5,60,0,50,45
4,2,1,3,3,2,2,2,1,1,2,...,3,2,1,2,2,3,2,1,2,2
5,2,1,3,3,1,1,3,1,1,1,...,3,3,1,5,2,4,1,1,2,2
6,5,5,2,3,3,2,1,5,2,2,...,3,3,2,2,2,2,3,4,2,2
7,5,1,3,1,5,5,3,5,1,1,...,5,2,4,1,1,4,1,1,1,1
8,1,1,3,2,3,3,3,1,5,5,...,3,2,3,5,5,3,2,3,5,5
9,-10,-10,10,10,0,0,10,0,10,0,...,10,10,10,10,0,10,10,-10,-10,-10
10,31419.7,43733.6,0,22302.6,26906.9,0,0,156163,0,16943,...,21911.6,28919.2,63350.6,15787.1,22863.4,8716.57,26060.1,38648.6,11601.5,33393.8
11,0,0,0,0,1,0,0,1,0,0,...,0,0,1,0,0,0,0,1,0,0
12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,1
14,0,0,0,0,0,0,0,0,1,1,...,1,0,0,0,0,0,1,0,0,0
15,0,0,0,0,0,0,0,0,0,0,...,0,1,0,1,0,0,0,0,0,0
16,0,1,1,0,0,1,1,0,0,0,...,0,0,0,0,0,1,0,0,0,0
17,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [27]:
df1 = pd.read_csv("OPC/clinical_info.csv")

In [28]:
df1.drop(['Split', 'Unnamed: 0'], axis = 1, inplace = True)
df1['time'] = df1['time'] * 10

In [30]:
df1.to_csv("OPC/clinical_info.csv")